export const products = new Map([[1,
    {
        productName: "Premium 1500",
        hamalrvatsSection: [
            "Քարշային մարտկոցներով",
            "Ամորտիզացման նոր համակարգով",
            "1500 Վտ հզորությամբ նոր էլեկտրաշարժիչով (ապահովում է 30% ավել պտտմանարդյունավետություն)",
            "15 դիոդ ունեցող առջևի լուսարձակով",
            "Լրացուցիչ նստատեղով՝ նախատեսված երկու ուղևորի համար",
            "Վարելու երեք ռեժիմով՝ դանդաղ, միջին, արագ",
            "Հետևի անիվների կատարելագործված ծածկադողերով"
        ],
        tableContents: {
            guyn: "Բաց մոխրագույն",
            brand: "aarba",
            sharjichHzorutyun: "1500 Վտ",
            martkocTesak: "XUPAI (72-60AH)",
            chapser: "3070x1280x1412 մմ",
            tapqiChapser: "1500x1200x340 մմ",
            bernataroxunakutyun: "500 կգ",
            maxSpeed: "35 կմ/ժ",
            mekLicqChanaparh: "90-100 կմ",
            azdHamakarg: "Այո",
            archevArgelak: "թմբուկային",
            hetevArgelak: "թմբուկային",
            qarshak: "Հետևի",
            mekLicqTevox: "6-8 ժամ",
            artadroxErkir: "Չինաստան",
            erashxiq: "12 ամիս",
            shahagortsum: "Ամբողջ տարի",
        },
        imageName: "product1.png"
    }],
    [2, {
        productName: "1200 Advanced",
        hamalrvatsSection: [
            "Քարշային մարտկոցներով",
            "Ամորտիզացման նոր համակարգով",
            "1500 Վտ հզորությամբ նոր էլեկտրաշարժիչով (ապահովում է 30% ավել պտտմանարդյունավետություն)",
            "15 դիոդ ունեցող առջևի լուսարձակով",
            "Լրացուցիչ նստատեղով՝ նախատեսված երկու ուղևորի համար",
            "Վարելու երեք ռեժիմով՝ դանդաղ, միջին, արագ",
            "Հետևի անիվների կատարելագործված ծածկադողերով"
        ],
        tableContents: {
            guyn: "Խակի",
            brand: "aarba",
            sharjichHzorutyun: "1200 Վտ",
            martkocTesak: "XUPAI (60V-58AH)",
            chapser: "3070x1280x1412 մմ",
            tapqiChapser: "1500x1200x340 մմ",
            bernataroxunakutyun: "500 կգ",
            maxSpeed: "35 կմ/ժ",
            mekLicqChanaparh: "65-70 կմ",
            azdHamakarg: "Այո",
            archevArgelak: "թմբուկային",
            hetevArgelak: "թմբուկային",
            qarshak: "Հետևի",
            mekLicqTevox: "6-8 ժամ",
            artadroxErkir: "Չինաստան",
            erashxiq: "12 ամիս",
            shahagortsum: "Ամբողջ տարի",
        },
        imageName: "product2.png"
    }],
    [3, {
        productName: "1000 Standard",
        hamalrvatsSection: [
            "Քարշային մարտկոցներով",
            "Ամորտիզացման նոր համակարգով",
            "1500 Վտ հզորությամբ նոր էլեկտրաշարժիչով (ապահովում է 30% ավել պտտմանարդյունավետություն)",
            "15 դիոդ ունեցող առջևի լուսարձակով",
            "Լրացուցիչ նստատեղով՝ նախատեսված երկու ուղևորի համար",
            "Վարելու երեք ռեժիմով՝ դանդաղ, միջին, արագ",
            "Հետևի անիվների կատարելագործված ծածկադողերով"
        ],
        tableContents: {
            guyn: "Վառ կապույտ",
            brand: "aarba",
            sharjichHzorutyun: "1000 Վտ",
            martkocTesak: "XUPAI (60V-45AH)",
            chapser: "2985x1180x1360 մմ",
            tapqiChapser: "1500x1100x490 մմ",
            bernataroxunakutyun: "400 կգ",
            maxSpeed: "30 կմ/ժ",
            mekLicqChanaparh: "55-65 կմ",
            azdHamakarg: "Այո",
            archevArgelak: "թմբուկային",
            hetevArgelak: "թմբուկային",
            qarshak: "Հետևի",
            mekLicqTevox: "6-8 ժամ",
            artadroxErkir: "Չինաստան",
            erashxiq: "12 ամիս",
            shahagortsum: "Ամբողջ տարի",
        },
        imageName: "product3.png"
    }]
])